language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script: pytest
env:
  global:
  - secure: 43ZPUA3lf+TkulB5vVOVjvPIZTXkUR3E852B9Cr+os9SYn5hZO2GHcMpDch1bdrjQwSIOSoHrJtB1eXHvFZTm1aJ7c5gk5cGZmuTr+wYuyVJinwe8waUGq1pXQpckgXx92cbG5Izdpo6xGDrtaXXyZVDqiU3FjkCNDYkCXiFfqgYSFb+VFjZcDhqMkIi+jRF9MWLfpg3MgeYiG1zbcqIAtyfjXlW1tRkRZamRse4WQkh8tW9LnvCt6TVMSi6kJdBPm21M6eZbBLggvqxj8f4BSEQJjw66Mg0CkKXZQpOTEZ55b8nhcSTAz0VYIJ100V9vXzrlnUz63YCu3zUczUwH7dNtjDtPKfdS083lSwwde4IwHOO/7+ym8ea7HCZPtf5Z9ZPTgenvUAIhwiEIPdPaL17zbhaJ2vU5vzkNj7kZjKbNJS79nyRztkD99Ir3yWIj69nMr9Wa+9q2NGdu7ucWKyu1tAzHS3lTu04+UcM8QF+3rcBOM+SJ0L1o8QTVj76T4OGca7nVAFsZD6i7XB0MH8w94GO0FbFYl7mSm0k+ll1tfMLO29zaB+GtiZhW9uK6YRevH5UBhnqTfX6HhbQRri1bSAKxm5JEVzF6ggYK/NRyxycNEXqBGdcobhoAYOj+fnsuVNoZg6StJD9r/uIv6S4iwPMgIKecJxbwYd+T6s=
  - secure: 3ZnGYc4zFVRQvc2/nWa6JCyGh00TvBsc2ec2gInXo1JIwqNgwK1/W5pgWE/zVuc/Fq5Lr8D6Dmv4frX99PmTxm+IKMd8uTt1JsVMimu2p3ZEvbbIsv/NVanGxTGh6i4C9i2Wo+1Hl1VT0EtRx8KJlto3eYSttNF+K7cg6W1St0g8jHbXRS2FqsTzDuoepByuwZ6qsvKWGTOCM4OTJdINSfzfGRo5IiyhzcesKqqrBIvNYw1vWAbdUGanIE85U0m1+mNTRZj+UumFKn3h6LzFur8jC6pYK8Ng9WBWoj/JQg3T7l28QHqK13+Bix88akC7an6ab6w87UPZCqwVnGMgQ8RGtr3zqUr14WXlcaTTRIoPf/5ute/TghdgDrwAfZSw4E6wZpKrT9JinAxXT87/3HqMg3XyP9NiCgW8+V6nDL5n7USYT91vj1vaVVquO6byEzdPYi0jIsf/A+wUGYFfPe5N0BGWzWkdpNFOwJkIu7DFJDAXjuykv3zFpRh/8tqMcccg07KqCduQHOBhxodTuxvPRolcDT2gOZh7y+00MfpEgVRMT0hTK7MwF/mtTHnNBXE4e271iPV2o5qR7LEwLYuVyDH3ujv5kEgGStmUZ8LdeR+cUHxSm5tDlzNCdbd+cFvrw26SH2n6Ws8FfGHTC6ATG2fvqLw+HzNhpzKgYrE=
before_install:
- openssl aes-256-cbc -K $encrypted_7fa766f91cf8_key -iv $encrypted_7fa766f91cf8_iv
  -in 39310-9864214f13c8.json.enc -out 39310-9864214f13c8.json -d
